name: ${project.name}
version: ${project.version}
main: net.mmogroup.mmolib.MMOLib
author: Indyuce
description: ${project.description}
api-version: 1.13
commands:
    exploreattributes:
        description: Explore player attributes.
permissions:
    mmolib.explore-attributes:
        default: op